name: Build and Push Docker

on:
  push:
    tags:
      - '*.*.*' # Trigger on version tags like 1.0.0

jobs:
  build-image-and-push-job:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v6
        
        - name: Build docjer image and push to Githun Registry
          uses: mr-smithers-excellent/docker-build-push@v6
          with:
            image: ${{ github.event.repository.name }}
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            
